package com.chunmi.annualconvention.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.chunmi.annualconvention.po.JobNums;

public interface JobNumsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	int insert(JobNums record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	int insertSelective(JobNums record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	JobNums selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	int updateByPrimaryKeySelective(JobNums record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cm_job_num
	 *
	 * @mbg.generated Wed Dec 27 13:13:48 CST 2017
	 */
	int updateByPrimaryKey(JobNums record);

	@Select("select count(1) from cm_job_num where job_num = #{jobNum} and del_flag = '0'")
	Integer existsJobNum(@Param("jobNum") String jobNum);
}