package com.chunmi.annualconvention.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.chunmi.annualconvention.po.Manager;

@Mapper
public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    Manager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_manager
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKey(Manager record);

    
    /**
     * 
     * @description: <p class="detail">根据名称查询管理员信息</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月11日-下午4:43:10
     * @param @param userName
     * @param @return
     * @return Manager
     */
    @Select("select * from cm_manager where user_name = #{userName}")
	Manager selectVoteUsersByName(@Param("userName")String userName);
}