package com.chunmi.annualconvention.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import com.chunmi.annualconvention.po.PrizeLevel;

@Mapper
public interface PrizeLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insert(PrizeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insertSelective(PrizeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    PrizeLevel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(PrizeLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_level
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKey(PrizeLevel record);

    /**
     * 
     * @description: <p class="detail">查询所有奖品等级</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月11日-下午6:29:47
     * @param @return
     * @return List<PrizeLevel>
     */
    @Select("select * from cm_prize_level where del_flag = '0'")
	List<PrizeLevel> selectAllPrizeLevel();

    /**
     * 
     * @description: <p class="detail">查询有奖品的奖项</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月20日-下午1:12:56
     * @param @return
     * @return List<PrizeLevel>
     */
	List<PrizeLevel> selectPrizeLevelWithPrize();
}