package com.chunmi.annualconvention.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.chunmi.annualconvention.po.Prize;

@Mapper
public interface PrizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insert(Prize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insertSelective(Prize record);

    /**
     * 
     * @description: <p class="detail">根据id删除奖品</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月12日-上午10:40:04
     * @param @param id
     * @param @return
     * @return Integer
     */
    @Update("update cm_prize set del_flag = '1' where id = #{id}")
	Integer delPrizeById(@Param("id") Long id);

    /**
     * 
     * @description: <p class="detail">查询奖品列表</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月12日-上午10:57:16
     * @param @return
     * @return List<Prize>
     */
	List<Prize> selectAllPrize();

	/**
	 * 
	 * @description: <p class="detail">根据奖品等级Id查询奖品id</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月19日-下午4:29:33
	 * @param @param prizeLevelId
	 * @param @return
	 * @return Long
	 */
	@Select("select id from cm_prize where prize_level_id = #{prizeLevelId} and del_flag = '0'")
	Long selectPrizeIdByPrizeLevelId(@Param("prizeLevelId")Long prizeLevelId);

	/**
	 * 
	 * @description: <p class="detail">根据奖项id获取奖品图片</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2018年1月15日-上午9:40:35
	 * @param @param prizeLevelId
	 * @param @return
	 * @return String
	 */
	@Select("select prize_pic from cm_prize where prize_level_id = #{prizeLevelId} and del_flag = '0'")
	String getPrizePicByPrizeLevelId(@Param("prizeLevelId")Long prizeLevelId);
}