package com.chunmi.annualconvention.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.chunmi.annualconvention.po.PrizeRecord;
import com.chunmi.annualconvention.vo.UsersVo;

@Mapper
public interface PrizeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insert(PrizeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insertSelective(PrizeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    PrizeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(PrizeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_prize_record
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKey(PrizeRecord record);

    /**
     * 
     * @description: <p class="detail">根据条件查询中奖纪录</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月19日-下午4:04:03
     * @param @param usersVo
     * @param @return
     * @return Integer
     */
	Integer selectPrizeRecordByCondition(@Param("usersVo")UsersVo usersVo);

	Integer insertPrizeRecordList(@Param("prizeRecordList") List<PrizeRecord> prizeRecordList);

	@Select("SELECT COUNT(1) FROM cm_prize_record r where r.prize_id = (SELECT id FROM cm_prize p where p.prize_level_id = #{prizeLevelId} AND p.del_flag = '0')")
	Integer selectPrizeRecordByPrizeLevelId(@Param("prizeLevelId")Long prizeLevelId);
	
	@Delete("delete from cm_prize_record")
	Integer clearAll();
}