package com.chunmi.annualconvention.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.chunmi.annualconvention.po.Users;
import com.chunmi.annualconvention.utils.PageRequest;
import com.chunmi.annualconvention.vo.UsersVo;

@Mapper
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    Users selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_users
     *
     * @mbg.generated Mon Dec 11 14:48:04 CST 2017
     */
    int updateByPrimaryKey(Users record);
    
    List<Users> selectAll();

    /**
     * 
     * @description: <p class="detail">根据条件查询满足条件的用户数量</p>
     * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
     * @date: 2017年12月13日-下午1:51:20
     * @param @param usersVo
     * @param @return
     * @return Long
     */
	Long selectUserCountsByCondition(@Param("usersVo")UsersVo usersVo);

	/**
	 * 
	 * @description: <p class="detail">根据查询条件分页查询用户</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月13日-下午2:13:49
	 * @param @param usersVo
	 * @param @param pageRequest
	 * @param @return
	 * @return List<UsersVo>
	 */
	List<UsersVo> selectUserListByCondition(@Param("usersVo")UsersVo usersVo, @Param("pageRequest")PageRequest pageRequest);

	/**
	 * 
	 * @description: <p class="detail">更新用户信息</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月13日-下午7:40:06
	 * @param @param usersVo
	 * @param @return
	 * @return Integer
	 */
	@Update("update cm_users set tel_num = #{usersVo.telNum},address = #{usersVo.address} where id = #{usersVo.id}")
	Integer updateUserInfo(@Param("usersVo")UsersVo usersVo);

	/**
	 * 
	 * @description: <p class="detail">根据条件查询将导出的用户信息</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月14日-上午11:05:10
	 * @param @param usesVo
	 * @param @return
	 * @return List<UsersVo>
	 */
	List<UsersVo> getExportUsersByCondition(@Param("usersVo") UsersVo usesVo);
	
	Users selectUserByWechat(String wechatNumber);
	
	Long queryCount();

	Integer updateUserPrizeStatus(@Param("getPrizeUserIds")Set<Long> getPrizeUserId);

	/**
	 * 
	 * @description: <p class="detail">查询中奖者信息</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月19日-下午5:57:53
	 * @param @param usersVo
	 * @param @param pageRequest
	 * @param @return
	 * @return List<UsersVo>
	 */
	List<UsersVo> selectGetPrizeUsers(@Param("usersVo")UsersVo usersVo, @Param("pageRequest")PageRequest pageRequest);

	/**
	 * 
	 * @description: <p class="detail">所有参加抽奖的人(还未获得奖品的人)</p>
	 * @author: <a href="mailto:sunny@chunmi.com ">sunny</a>
	 * @date: 2017年12月19日-下午6:53:19
	 * @param @return
	 * @return List<Users>
	 */
	List<Users> selectAllWithNoPrize();

	@Update(" UPDATE cm_users SET remark = null ")
	Integer updateUsersRemark();

	@Select("select count(1) from cm_users where job_num = #{jobNum}")
	Integer existsUsers(@Param("jobNum")String jobNum);
	
	Users selectUserByNum(String jobNum);
	 
	
}