# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://10.78.1.143:3306/cm_annual_convention?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: chunmi_store
    password: M@!chunmi_m_795146
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 800
      min-idle: 50
      initial-size: 200
      
  redis:
    host: 10.78.1.149
    port: 6379
    database: 1
    password: 
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0