# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://10.0.10.99:3306/cm_annual_convention?useUnicode=true&characterEncoding=UTF-8
    username: chunmi_test
    password: chunmitest
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 800
      min-idle: 50
      initial-size: 200
  
  redis:
    host: 10.0.10.60
    port: 6379
    database: 1
    password: 
    timeout: 0
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8   # 连接池中的最大空闲连接
      min-idle: 0   # 连接池中的最小空闲连接